# Generated by Django 6.0.2 on 2026-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='en_meaning',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
