# Generated by Django 6.0.2 on 2026-03-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_question_en_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='jlpt_level',
            field=models.CharField(blank=True, choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='jp_sentence',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='th_sentence',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
